---
# handlers file for ansible-role-haproxy

- name: reload haproxy
  service:
    name: "{{ haproxy_service_name }}"
    state: reloaded

- name: restart rsyslog
  service:
    name: "{{ haproxy_rsyslog_service_name }}"
    state: restarted

